//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellableMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderQuestions = new HashSet<OrderQuestion>();
        }
    
        public int OrderID { get; set; }
        public decimal Amount { get; set; }
        public int UserId { get; set; }
        public int OrderStatusId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> PromoId { get; set; }
        public Nullable<int> UserPhoneId { get; set; }
        public string PaymentUserName { get; set; }
        public string USPSTrackingId { get; set; }
        public string MailingLabel { get; set; }
    
        public virtual User User { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Promo Promo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderQuestion> OrderQuestions { get; set; }
    }
}
