//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellableMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPhone()
        {
            this.UserAnswers = new HashSet<UserAnswer>();
        }
    
        public int UserPhoneId { get; set; }
        public int UserId { get; set; }
        public int PhoneId { get; set; }
        public int CarrierId { get; set; }
        public int VersionId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual PhoneVersion PhoneVersion { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAnswer> UserAnswers { get; set; }
    }
}
